<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="1" hostname="DESKTOP-O1U6M3B" failures="1" tests="7" name="C:/Users/KAPIL/IdeaProjects/SeleniumWithMavenProj" time="0.148" errors="0" timestamp="2025-04-09T18:08:09 IST">
  <testcase classname="basicoftestng.PriorityEx" name="testCaseX" time="0.012"/>
  <testcase classname="basicoftestng.PriorityEx" name="testCaseE" time="0.0"/>
  <testcase classname="basicoftestng.PriorityEx" name="testCaseP" time="0.02">
    <skipped/>
  </testcase> <!-- testCaseP -->
  <testcase classname="basicoftestng.PriorityEx" name="testCaseP" time="0.001">
    <skipped/>
  </testcase> <!-- testCaseP -->
  <testcase classname="basicoftestng.PriorityEx" name="testCaseP" time="0.002">
    <skipped/>
  </testcase> <!-- testCaseP -->
  <testcase classname="basicoftestng.PriorityEx" name="testCaseP" time="0.002">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1590)
at org.testng.Assert.assertTrue(Assert.java:57)
at org.testng.Assert.assertTrue(Assert.java:67)
at basicoftestng.PriorityEx.testCaseP(PriorityEx.java:20)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:687)
at org.testng.internal.invokers.TestInvoker.retryFailed(TestInvoker.java:269)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:76)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:995)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:741)
at org.testng.TestRunner.run(TestRunner.java:616)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:65)
at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:105)
]]>
    </failure>
  </testcase> <!-- testCaseP -->
  <testcase classname="basicoftestng.PriorityEx" name="testCaseY" time="0.0"/>
  <testcase classname="basicoftestng.PriorityEx" name="testCaseB" time="0.0">
    <ignored/>
  </testcase> <!-- testCaseB -->
</testsuite> <!-- C:/Users/KAPIL/IdeaProjects/SeleniumWithMavenProj -->
